// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/material.dart';
import 'package:powerpal/main.dart';
 // ignore: unused_import
 import 'firebase_options.dart';

   void main() async{
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,);
   runApp(MyApp());
   }

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMEV_u1THVPYUD-7fD41wpm0S5eEn8mUA',
    appId: '1:833819821331:web:e872255548e43918f386e6',
    messagingSenderId: '833819821331',
    projectId: 'powerpal-8a53c',
    authDomain: 'powerpal-8a53c.firebaseapp.com',
    storageBucket: 'powerpal-8a53c.appspot.com',
    measurementId: 'G-PTFWXXYVH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWIxP-9njOGE1AIjRjVrkkE-62dG4sKPA',
    appId: '1:833819821331:android:10d7cfcba435b94ef386e6',
    messagingSenderId: '833819821331',
    projectId: 'powerpal-8a53c',
    storageBucket: 'powerpal-8a53c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdzLMPBZjpTwd1i6XeP3bnyCsaWBM3VSA',
    appId: '1:833819821331:ios:363e73782716d538f386e6',
    messagingSenderId: '833819821331',
    projectId: 'powerpal-8a53c',
    storageBucket: 'powerpal-8a53c.appspot.com',
    iosClientId: '833819821331-l279rde5sf0igkj1i3h61etehslpqqbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.powerpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdzLMPBZjpTwd1i6XeP3bnyCsaWBM3VSA',
    appId: '1:833819821331:ios:363e73782716d538f386e6',
    messagingSenderId: '833819821331',
    projectId: 'powerpal-8a53c',
    storageBucket: 'powerpal-8a53c.appspot.com',
    iosClientId: '833819821331-l279rde5sf0igkj1i3h61etehslpqqbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.powerpal',
  );
}
